package com.example.dependencyentity;// default package
// Generated 9 Jul, 2017 10:23:33 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductDetailsId generated by hbm2java
 */
@Embeddable
public class ProductDetailsId implements java.io.Serializable {

	private String sellerId;
	private String productIsbnId;

	public ProductDetailsId() {
	}

	public ProductDetailsId(String sellerId, String productIsbnId) {
		this.sellerId = sellerId;
		this.productIsbnId = productIsbnId;
	}

	@Column(name = "seller_id", nullable = false, length = 256)
	public String getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(String sellerId) {
		this.sellerId = sellerId;
	}

	@Column(name = "product_isbn_id", nullable = false)
	public String getProductIsbnId() {
		return this.productIsbnId;
	}

	public void setProductIsbnId(String productIsbnId) {
		this.productIsbnId = productIsbnId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductDetailsId))
			return false;
		ProductDetailsId castOther = (ProductDetailsId) other;

		return ((this.getSellerId() == castOther.getSellerId()) || (this.getSellerId() != null
				&& castOther.getSellerId() != null && this.getSellerId().equals(castOther.getSellerId())))
				&& ((this.getProductIsbnId() == castOther.getProductIsbnId())
						|| (this.getProductIsbnId() != null && castOther.getProductIsbnId() != null
								&& this.getProductIsbnId().equals(castOther.getProductIsbnId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSellerId() == null ? 0 : this.getSellerId().hashCode());
		result = 37 * result + (getProductIsbnId() == null ? 0 : this.getProductIsbnId().hashCode());
		return result;
	}

}
