package com.example.entity;// default package
// Generated 9 Jul, 2017 10:23:33 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.*;

/**
 * ProductDetails generated by hbm2java
 */
@Entity
@Table(name = "product_details", catalog = "seller_product")
public class ProductDetails implements java.io.Serializable {

	private ProductDetailsId id;
	private String productName;
	private double productPrice;
	private Integer productQuantity;
	private Integer productSellQuantity;
	private Byte isProductActive;

	public ProductDetails() {
	}

	public ProductDetails(ProductDetailsId id, String productName, double productPrice) {
		this.id = id;
		this.productName = productName;
		this.productPrice = productPrice;
	}

	public ProductDetails(ProductDetailsId id, String productName, double productPrice, Integer productQuantity,
                          Integer productSellQuantity, Byte isProductActive) {
		this.id = id;
		this.productName = productName;
		this.productPrice = productPrice;
		this.productQuantity = productQuantity;
		this.productSellQuantity = productSellQuantity;
		this.isProductActive = isProductActive;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sellerId", column = @Column(name = "seller_id", nullable = false, length = 256)),
			@AttributeOverride(name = "productIsbnId", column = @Column(name = "product_isbn_id", nullable = false)) })
	public ProductDetailsId getId() {
		return this.id;
	}

	public void setId(ProductDetailsId id) {
		this.id = id;
	}

	@Column(name = "product_name", nullable = false, length = 10)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_price", nullable = false, precision = 22, scale = 0)
	public double getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(double productPrice) {
		this.productPrice = productPrice;
	}

	@Column(name = "product_quantity")
	public Integer getProductQuantity() {
		return this.productQuantity;
	}

	public void setProductQuantity(Integer productQuantity) {
		this.productQuantity = productQuantity;
	}

	@Column(name = "product_sell_quantity")
	public Integer getProductSellQuantity() {
		return this.productSellQuantity;
	}

	public void setProductSellQuantity(Integer productSellQuantity) {
		this.productSellQuantity = productSellQuantity;
	}

	@Column(name = "is_product_active")
	public Byte getIsProductActive() {
		return this.isProductActive;
	}

	public void setIsProductActive(Byte isProductActive) {
		this.isProductActive = isProductActive;
	}

}